from launch import LaunchDescription
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os

def generate_launch_description():
    """
    Launch file for VLA Integration
    Launches all nodes required for Vision-Language-Action integration
    """
    return LaunchDescription([
        # Whisper Client Node - handles audio recording and transcription
        Node(
            package='std_msgs',  # Using std_msgs as placeholder, would be your package
            executable='whisper_client',  # This would be your executable name
            name='whisper_client',
            output='screen',
            parameters=[
                # Add any parameters your node needs
            ]
        ),
        
        # NLP Processor Node - processes transcribed text with GPT-4
        Node(
            package='std_msgs',  # Using std_msgs as placeholder, would be your package
            executable='nlp_processor',  # This would be your executable name
            name='nlp_processor',
            output='screen',
            parameters=[
                # Add any parameters your node needs
            ]
        ),
        
        # VLA Action Server - executes actions generated by NLP processor
        Node(
            package='std_msgs',  # Using std_msgs as placeholder, would be your package
            executable='vla_action_server',  # This would be your executable name
            name='vla_action_server',
            output='screen',
            parameters=[
                # Add any parameters your node needs
            ]
        )
    ])